spring:
  application:
    name: Mini Cinema API
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_cinema
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8
server:
  port: 8080
app:
  secret-key: 8d46a5159527e98043092e5fb95f1b88f28e3918dfdf8171a820eff88664b88a
  refresh-token-expiration: 604800000 # 7 days
  access-token-expiration: 604800000 # 7 days
  production: false
  password-reset-token-expiration: 900000 # 15 minutes
  email-from: no-reply@minicenima.com
  email-reply-to: dev.doansamquoc@gmail.com
  frontend-url: http://localhost:5173